# Generated by Django 5.0.7 on 2024-07-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
            ],
        ),
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='Description')),
                ('embedding', models.JSONField(null=True, verbose_name='Embedding')),
                ('img_1', models.ImageField(upload_to='media/product', verbose_name='Image main')),
                ('img_2', models.ImageField(upload_to='media/product', verbose_name='image 2')),
                ('img_3', models.ImageField(upload_to='media/product', verbose_name='image 3')),
                ('addtime', models.DateField(auto_now_add=True, verbose_name='add data')),
                ('price_now', models.FloatField(verbose_name='Price now')),
                ('discount', models.FloatField(verbose_name='discount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categorry', to='core.maincategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Companny', to='core.company')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
